### ISSUE TITLE
Code of Conduct refers to positions that no longer exist

### ISSUE THREAD

**Issue by lawrence-forooghian** [dxw/.github#2]
> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to dxw’s Chief Technology Officer at [code-of-conduct@dxw.com](mailto:code-of-conduct@dxw.com). If a complaint relates to the conduct of the Chief Technology Officer, then complaints may be reported to the Managing Director at [code-of-conduct-md@dxw.com](mailto:code-of-conduct-md@dxw.com). The current holders of these roles can be found on [dxw’s people page](https://www.dxw.com/our-people/).

Neither the Chief Technology Officer nor Managing Director titles exist on the people page any more.

**Comment by lawrence-forooghian** [comment]
Happy to see somebody saw the issue, thanks @jdudley1123! Just a heads-up that there’s a typo in the new text ("techincal").

**Comment by jdudley1123** [comment]
Doh! Fixed now. Thanks for flagging it!
